import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import { Footer } from '@/components/Footer';
import { Navbar } from '@/components/Navbar';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';
import { MENU_ITEMS } from '@/lib/constants';

const robotoSans = Roboto({
	variable: '--font-roboto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${robotoSans.variable} bg-zinc-50 px-20 font-sans antialiased dark:bg-black`} suppressHydrationWarning>
				<div className='flex min-h-screen flex-col bg-background'>
					<header className='flex h-18 items-center justify-between px-24 pt-6 pb-2'>
						<div className='size-5 opacity-0'></div>
						<Navbar links={MENU_ITEMS} />
						<ThemeSwitcher />
					</header>
					<main className='flex-1'>{children}</main>
					<Footer links={MENU_ITEMS} />
				</div>
			</body>
		</html>
	);
}
