import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import Footer from '@/components/Footer/Footer';
import { MENU_ITEMS } from '@/lib/types';

const robotoSans = Roboto({
	variable: '--font-roboto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${robotoSans.variable} min-h-screen bg-background font-sans text-foreground antialiased`}>
				{children}
				<Footer links={MENU_ITEMS} />
			</body>
		</html>
	);
}
